#!/bin/bash
#
# Recommended versions:
#
#   * GCC: gcc-arm-none-eabi-7-2017-q4-major
#
#   * CC32xx SDK: simplelink_cc32xx_sdk_2_10_00_04
#
#   * MSP432E4 SDK: simplelink_msp432e4_sdk_2_10_00_17
#
#   * MSP432P4 SDK: simplelink_msp432p4_sdk_2_10_00_14
#
#   * CC13xx/CC26xx SDK: ???
#

canonicalize_path() {
    if [ -d "$1" ]; then
        _canonicalize_dir_path "$1"
    else
        _canonicalize_file_path "$1"
    fi
}

_canonicalize_dir_path() {
    (cd "$1" 2>/dev/null && pwd -P)
}

_canonicalize_file_path() {
    local dir file
    dir=$(dirname -- "$1")
    file=$(basename -- "$1")
    (cd "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd -P)" "$file")
}

main()
{
    if ! cd ${1:-.}
    then
	echo "error: could not change directory" 1>&2
	exit 1
    fi

    if test -d gcc-arm-none-eabi-7*
    then
	echo GCC_ARMCOMPILER = $(canonicalize_path ./gcc-arm-none-eabi*)
    else
	echo "error: missing GCC ARM" 1>&2
	exit 1
    fi

    if test -d xdctools_3_*
    then
	echo XDC_INSTALL_DIR = $(canonicalize_path ./xdctools_3_50*)
    else
	echo "error: missing XDCtools" 1>&2
	exit 1
    fi

    for sdk in simplelink*
    do
        if test -d $sdk
        then
            SDK=$(echo $sdk | tr "[:lower:]" "[:upper:]")
            echo ${SDK%%_?_??_*}"_INSTALL_DIR" = $(canonicalize_path $sdk)
        fi
    done
}

main $*
