import network

w = network.WLAN()
w.active(True)


# This is example radius server cert chain for testing.  Needs to be replaced with real chain.

certdata = "\
-----BEGIN CERTIFICATE-----\n\
MIID2jCCAsKgAwIBAgIBATANBgkqhkiG9w0BAQsFADCBkzELMAkGA1UEBhMCRlIx\n\
DzANBgNVBAgTBlJhZGl1czESMBAGA1UEBxMJU29tZXdoZXJlMRUwEwYDVQQKEwxF\n\
eGFtcGxlIEluYy4xIDAeBgkqhkiG9w0BCQEWEWFkbWluQGV4YW1wbGUuY29tMSYw\n\
JAYDVQQDEx1FeGFtcGxlIENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0xODA4MTQy\n\
MDQyMDNaFw0xOTA4MTQyMDQyMDNaMHwxCzAJBgNVBAYTAkZSMQ8wDQYDVQQIEwZS\n\
YWRpdXMxFTATBgNVBAoTDEV4YW1wbGUgSW5jLjEjMCEGA1UEAxMaRXhhbXBsZSBT\n\
ZXJ2ZXIgQ2VydGlmaWNhdGUxIDAeBgkqhkiG9w0BCQEWEWFkbWluQGV4YW1wbGUu\n\
Y29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA08L2FwpGEA4YbmqJ\n\
FBq44IAAIz3x0X4XDYXSbqH8Y6KPBRFlM6WtOiJ+vtgzATOepSdDuQIf+R/LTKTM\n\
rrv7cpKyhASuptiBNutxXqohBcg9FqxSgukKN3JWk+l3ZbvZM6j62+UApRqr6EQW\n\
lPhff11C32CSmHUbklbBSl/O9ZJTiaTAKJbbo6pBl+YcmabnaDpoSmHnDv+Rwu55\n\
kbRYSrCDz+DiU5G1fSEfGISKTqfB8hbPBMr2VmR2toepydsuuxCSkbDSlgQNii87\n\
JWhAW2Z6VY/JgzOVzCXJRo7tc9Ljeu7nWM4X8S1wDe0QVlrUvNQ8GDRg5TcOW5Rd\n\
Al1kvwIDAQABo08wTTATBgNVHSUEDDAKBggrBgEFBQcDATA2BgNVHR8ELzAtMCug\n\
KaAnhiVodHRwOi8vd3d3LmV4YW1wbGUuY29tL2V4YW1wbGVfY2EuY3JsMA0GCSqG\n\
SIb3DQEBCwUAA4IBAQBwNgHQfsSnFgl3f/iWh6a+7Usp+aqh+VGBJzikAFcJgGMm\n\
bDGc5ysJAqBsvJYbsf/GFkHWJm+A52m6uM6o2rtEkKhhRhEFJArIXdv5kQ5vatjm\n\
wsXS9ZAjz8EoXeXn64FZwbdrrz/1UYeMNtCq5atG2rGR4lH2/q1kDcYHLPhucyjD\n\
YkIg6MsVbFnzralitVVO5ddPjM6CDK4voBKqJ2Q/ydgQEmbmLuI6SgxEHLe/ZX71\n\
1c284niOKEQuhVqAjZlsvgc+CmYaGbLiNhEOmdzj17VGdREcTKHCiV0t35bKAQS+\n\
FMeuK04qCCYI20tgnXJZvd2A3grwroeOJUBTKyYd\n\
-----END CERTIFICATE-----\n\
-----BEGIN CERTIFICATE-----\n\
MIIE4TCCA8mgAwIBAgIJAITsNWa8sUmpMA0GCSqGSIb3DQEBCwUAMIGTMQswCQYD\n\
VQQGEwJGUjEPMA0GA1UECBMGUmFkaXVzMRIwEAYDVQQHEwlTb21ld2hlcmUxFTAT\n\
BgNVBAoTDEV4YW1wbGUgSW5jLjEgMB4GCSqGSIb3DQEJARYRYWRtaW5AZXhhbXBs\n\
ZS5jb20xJjAkBgNVBAMTHUV4YW1wbGUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4X\n\
DTE4MDgxNDIwNDIwM1oXDTE5MDgxNDIwNDIwM1owgZMxCzAJBgNVBAYTAkZSMQ8w\n\
DQYDVQQIEwZSYWRpdXMxEjAQBgNVBAcTCVNvbWV3aGVyZTEVMBMGA1UEChMMRXhh\n\
bXBsZSBJbmMuMSAwHgYJKoZIhvcNAQkBFhFhZG1pbkBleGFtcGxlLmNvbTEmMCQG\n\
A1UEAxMdRXhhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3\n\
DQEBAQUAA4IBDwAwggEKAoIBAQDtWFAYckfxVYIbAE940TLHNZ0BySXyrJRBBQSd\n\
KDOiaViSQcrEUWUrt8FMtKc8IpKSRlzAEH82lMAhtG7zSEYNng19Xp7zy6G/Vhxf\n\
dT568rFHnTvU8HTwcg5vHokHMvnPuvGtnd9/GtFTXOfuH9nioubOa6MVTQ251lUT\n\
8rSExanGGzH2d9kKXuKdFOUvMM6KnmjaZIY2D0bczbC4FM/VGAi2KX2Si4k/0oay\n\
eWAxLzN8KBpz2BRibQQ8pt3oUBxCWOXzZsnSGqsSFEHhANm73YQ2eCRSWOtbOsK+\n\
5qmPIZ0BZ4fyrozfXA2LvEtyWvJt9+jhivSar1Vm8QyV3mePAgMBAAGjggE0MIIB\n\
MDAdBgNVHQ4EFgQUoTEy4mtInVKMuJ5mIdjq3bNZ8XswgcgGA1UdIwSBwDCBvYAU\n\
oTEy4mtInVKMuJ5mIdjq3bNZ8XuhgZmkgZYwgZMxCzAJBgNVBAYTAkZSMQ8wDQYD\n\
VQQIEwZSYWRpdXMxEjAQBgNVBAcTCVNvbWV3aGVyZTEVMBMGA1UEChMMRXhhbXBs\n\
ZSBJbmMuMSAwHgYJKoZIhvcNAQkBFhFhZG1pbkBleGFtcGxlLmNvbTEmMCQGA1UE\n\
AxMdRXhhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHmCCQCE7DVmvLFJqTAMBgNV\n\
HRMEBTADAQH/MDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly93d3cuZXhhbXBsZS5j\n\
b20vZXhhbXBsZV9jYS5jcmwwDQYJKoZIhvcNAQELBQADggEBAMKTscJa6/dyV4tg\n\
q96ZT9ZRXGvUeDjGRV4Bc2QypBZsaVjOU9OMFoZYDZXu4JHNm6f+b3vxAaqZbbJU\n\
IGzhzpAVAwaoWUeVFlzjbEo4ZwIwoFntyubP985aAPKxfI3aoV0fMSA227OvS0en\n\
8hPzKAqsubsbFQLGrJ8gkG98x7BvyYRdJACfpuvMFVtZzPmkLKpneI7857rlZb1O\n\
eYZMRRQxuHHLQ+J0iCMAC9IE2GMysuVVmzbOV13+bkK3XK0p+lQtQNyBuj0XSfon\n\
W1Jbie5Attojvo/HP+o4Wu33en95hjZVzKE6hjBAYb96QWQcGjBsjj0Pn3yYhU1B\n\
73kEdFQ=\n\
-----END CERTIFICATE-----\n\
"

print("Writing Cert Data")
print(certdata)

# This file can be der or pem, and needs to contain the chain back to the root ca
# doesn't need to include the server cert itself
filehandle, token = w.fsopen("/sys/cert/ca.der", w.FS_WRITE)
print("File Handle : %d, access token %d" % (filehandle, token))

len = w.fswrite(filehandle, 0, certdata)

print("Written %d bytes" % len)

#w.fsread(filehandle, 0, 2048);

w.fsclose(filehandle)


