print("Running Wlan Connect Test")
from network import WLAN
from time import sleep
print("Starting WLAN")
wlan = WLAN(0)
wlan.active(True)
print("Setting Time")
wlan.rtc_set((2018, 8, 27, 10, 00))
print(wlan.rtc_now())
print("Scanning")
print(wlan.scan())
sleep(1)
print(wlan.scan())
sleep(1)
print("Connecting...")
wlan.connect("MYENTAP", "entpassword", enterprise=True, entuser="entuser", entmethod=wlan.EAP_METHOD_PEAP0_MSCHAPv2, entserverauth=True)
sleep(1)
print("connected status is ")
print(wlan.isconnected())
print("ifconfig status is ")
sleep(1)
print(wlan.ifconfig())
print("done")
