#!/bin/bash
#
# Recommended versions:
#
#   * GCC: gcc-arm-none-eabi-7-2017-q4-major
#          https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2?revision=375265d4-e9b5-41c8-bf23-56cbe927e156?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2017-q4-major
#
#   * XDC: xdctools_3_50_05_12
#          http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/rtsc/3_50_05_12/exports/xdccore/xdctools_3_50_05_12_core_linux.zip
#
#   * CC32xx SDK: simplelink_cc32xx_sdk_2_10_00_04
#
#   * MSP432E4 SDK: simplelink_msp432e4_sdk_2_10_00_17
#
#   * MSP432P4 SDK: simplelink_msp432p4_sdk_2_10_00_14
#
#   * CC13xx/CC26xx SDK: ???
#

#rm -f defs.mk

if test -d gcc-arm-none-eabi-7*
then
    echo GCC_ARMCOMPILER = $(readlink ./gcc-arm-none-eabi-7*)
else
    echo "error: missing GCC ARM" 1>&2
    exit 1
fi

if test -d xdctools_3_50*
then
    echo XDC_INSTALL_DIR = $(readlink ./xdctools_3_50*)
else
    echo "error: missing XDCtools" 1>&2
    exit 1
fi

for soc in cc32xx cc13x2 msp432e4 msp432p4
do
    if test -d simplelink_$soc"_sdk_2_10"*
    then
        SOC=`echo $soc | awk '{print toupper($0)}'`
        echo SIMPLELINK_$SOC"_SDK_INSTALL_DIR" = $(readlink simplelink_$soc"_sdk_2_10"*)
    fi
done

if test -d simplelink_sdk_wifi*
then
    echo SIMPLELINK_MSP432_SDK_WIFI_PLUGIN_INSTALL_DIR = $(readlink ./simplelink_sdk_wifi*)
fi
